### ISSUE TITLE
Wrappered pylint don't found config file in subdirectory

### ISSUE THREAD

**Issue by AfsmNGhr** [AfsmNGhr/dockemacs#25]
`
DEBUG: You may test it with below command
CMD: ssh afsmnghr@127.1 -p 22 -tt docker exec -it example_example_1 pylint --reports=n --output-format=text --msg-template={path}:{line}:{column}:{C}:{symbol}:{msg}
--rcfile=/home/example/.pylintrc /home/example/core/config.py
`

`
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.7/site-packages/pylint/__init__.py", line 19, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/pylint/lint.py", line 1348, in __init__
    linter.read_config_file(verbose=self.verbose)
  File "/usr/local/lib/python3.7/site-packages/pylint/config.py", line 654, in read_config_file
    raise IOError("The config file {:s} doesn't exist!".format(config_file))
OSError: The config file /home/example/.pylintrc doesn't exist!
`

**Comment by AfsmNGhr** [comment]
Works with pylint==2.2.2.
